### ISSUE TITLE
Issue with library name

### ISSUE THREAD

**Issue by cmaglie** [thomasfredericks/wemos_matrix_gfx#3]
Hi @thomasfredericks 

we have detected that you changed the name of the library in `library.properties` from
  `WEMOS Matrix Compatible With Adafruit GFX Library`
to
  `wemos_matrix_gfx - WEMOS Matrix Adafruit GFX`
and again to
  `Wemos Matrix Adafruit GFX`
is that right?
We are introducing a change in the library manager that forbids this kind of changes and ignore the releases with the name that differs from the name registered in the library index.

Is it ok for you to keep the new name `Wemos Matrix Adafruit GFX`? The older releases with a different name will be ignored by the library manager. In absence of an answer from you we will proceed with this proposal next week.

See also: https://github.com/arduino/Arduino/issues/7127

```
JOB 1182 - 2018/01/15 15:45:27 Scraping https://github.com/thomasfredericks/wemos_matrix_gfx.git
JOB 1182 - 2018/01/15 15:45:28 Checking out tag: v1.0
JOB 1182 - 2018/01/15 15:45:28 Release WEMOS Matrix Compatible With Adafruit GFX Library:1.0.0 already loaded, skipping
JOB 1182 - 2018/01/15 15:45:28 Checking out tag: v1.1
JOB 1182 - 2018/01/15 15:45:28 Release wemos_matrix_gfx - WEMOS Matrix Adafruit GFX:1.1.0 has wrong library name, should be WEMOS Matrix Compatible With Adafruit GFX Library
JOB 1182 - 2018/01/15 15:45:28 Checking out tag: v1.2
JOB 1182 - 2018/01/15 15:45:28 Release Wemos Matrix Adafruit GFX:1.2.0 has wrong library name, should be WEMOS Matrix Compatible With Adafruit GFX Library
```

**Comment by thomasfredericks** [comment]
@cmaglie Yes, I had to change the name because it was too long for the Arduino IDE. Yes, the final name is:
`Wemos Matrix Adafruit GFX`
