### ISSUE TITLE
.setRotation() doesn't work

### ISSUE THREAD

**Issue by SierraLimaOscar** [thomasfredericks/wemos_matrix_gfx#4]
Hi Thomas,
Using your example (wemos_matrix_gfx_demo.ino)  the orientation of the word "world" just doesn't change. The same is true for a software of mine in which I am trying to use the same property.
I'm using a Wemos D1mini Pro v1.10 + Wemos matrix mini shield and am getting the same results with the Arduino IDE and with Platformio.

**Comment by thomasfredericks** [comment]
Hi, I did notice this, but don't know how to fix it.
