### ISSUE TITLE
Missing degree symbol in replacement character list

### ISSUE THREAD

**Issue by Joennuh** [thomasfredericks/wemos_matrix_gfx#5]
Is it possible to add the degree symbol to the list with replacement characters?
I have tried iot to do it by my self but I couldn't get it to work.
I'd like to be able to show a temperature on the display followed by the degree symbol anc C (from Celcius).
Example: 21,3°C

**Comment by thomasfredericks** [comment]
Hi,
You should the Adafruit GFX Library developer as this library simply extends it.
